### ISSUE TITLE
Does not bind to input/textarea?

### ISSUE THREAD

**Issue by fbm-static** [mikecrittenden/chrome-shortkeys#21]
1. Add a keybinding (eg. ctrl+enter)
2. run javascript (alert('df');)
3. focus on textarea
4. press ctrl+enter
5. nothing happens

**Comment by mikecrittenden** [comment]
That's by design - keyboard shortcuts don't run in form elements, so that you can have keyboard shortcuts like "h" or "shift+j" without making them run when you're just trying to fill out a form.

We do need to add a per-shortcut option though, like a checkbox that says "enable this shortcut when focused on form elements". That's what this issue is for: https://github.com/mikecrittenden/chrome-shortkeys/issues/6 -- I just haven't had time to work on it for a while.
