### ISSUE TITLE
Does not work when URL bar is focused or on the new tab page

### ISSUE THREAD

**Issue by allantokuda** [mikecrittenden/chrome-shortkeys#44]
I'm on Ubuntu Linux 16.04 LTS, Chrome Version 54.0.2840.100 (64-bit)

Steps to reproduce:
* Add shortcut for `alt+t` mapped to "New Tab"
* Save, quit browser, restart
* Press `alt+t` => Expected new tab to open, but nothing happens
* Click in webpage area
* Press `alt+t` => now new tab opens!
* Press `alt+t` again => another tab does not open
* Click in webpage area, then press `alt+t` => new tab opens

It appears that either window page body area must be focused, or the URL bar must not be focused, for the keybinding to take effect. This limits the usefulness of the extension for me. My goal was to make my home Linux computer work more similarly to my work Mac computer, where Cmd+T and Cmd+W open and close Chrome tabs. On Linux, the "Alt" key is located where the Mac "Cmd" key would be.

**Comment by AlexByte** [comment]
You can do it with xbindkeys:
[app-specific shortcut remap](https://askubuntu.com/questions/97213/application-specific-key-combination-remapping)
[bind keys to other keys..](http://askubuntu.com/a/254425/575173)

**Comment by mikecrittenden** [comment]
The only way for Shortkeys to support this would be if we started using the built in support that Chrome provides for keyboard shortcuts for extensions. https://developer.chrome.com/extensions/commands

The downsides to this approach are:

- Shortcuts added there can't have any custom configuration (such as adding custom JS to run, or a specific bookmark to load, or all of the other Shortkeys features besides just basic commands)
- Shortcuts added there MUST use either ctrl or alt, so there's less freedom.

I've been considering trying to support both ways - allow for simple shortcuts to be created using the built in Chrome way (so that it works on the new tab page and URL bar, etc.) but still allowing the custom UI for more advanced usage.

**Comment by mikecrittenden** [comment]
I just pushed some code that adds support for Chrome's keyboard shortcuts UI to work around this, for commands where it's possible. Docs here: https://github.com/mikecrittenden/chrome-shortkeys/wiki/How-To-Use-Shortkeys#chromes-keyboard-shortcuts-settings-vs-shortkeys-settings

This will be included in the next release. I'll leave this open until then. Feel free to try out the commit above and comment though, if you'd like.

**Comment by AlexByte** [comment]
Quickly

**Comment by mikecrittenden** [comment]
Ok just deployed 2.0.20 which contains this change. Now, every shortcut that doesn't require its own config has an option to be run from Chrome's built in keyboard shortcuts UI rather than the Shortkeys UI. If you try to add one from the Shortkeys config which is supported in Chrome's built in config, then a message pops up alerting you that you can also add that from Chrome's built in config if you want to, with a link to the docs.

The docs on the pros and cons of each are here: https://github.com/mikecrittenden/chrome-shortkeys/wiki/FAQs-and-Troubleshooting#do-i-use-chromes-keyboard-shortcuts-settings-or-the-shortkeys-options-page
