### ISSUE TITLE
Custom JS commands can no longer access libraries (jQuery, etc.) on the page they're running on

### ISSUE THREAD

**Issue by sonnyd64** [mikecrittenden/chrome-shortkeys#83]
Earlier today my Javascript shortcuts were working normally but it seems that my extension updated at some point this afternoon and they've been non-functional ever since.

**Comment by mikecrittenden** [comment]
Well that's no good. I'll investigate this in a couple hours.

**Comment by araadt** [comment]
I'll second this.

**Comment by mikecrittenden** [comment]
So far I'm unable to reproduce this. Some questions:

1. Do other non-JS shortcuts still work?
2. When you go into the settings, is your JS still there in the text box?
3. Does it work after re-saving it from there?

**Comment by sonnyd64** [comment]
1. Yep, just created a bookmark shortcut and it works as expected.
2. Weirdly, when the shortcuts are first expanded the "Javascript code to run" textbox is blank, but when I click on it the expected code does appear.  Additionally the "blank" textbox has a vertical scrollbar that hides itself once I click the element and the JS appears.
3. Re-saving doesn't seem to have any impact, my shortcuts are still broken.
4. I do seem to be getting the following error in the console when a JS shortcut fails:

> Uncaught ReferenceError: $ is not defined
>     at <anonymous>:1:1
> (anonymous) @ VM658:1

**Comment by mikecrittenden** [comment]
@sonnyd64 ahh so does your JS use the $? I'm assuming that's meant to be a pointer to jQuery which already is supposed to exist on the page?

**Comment by mikecrittenden** [comment]
Does a simple alert('hi') work fine?

**Comment by sonnyd64** [comment]
Oh yeah, completely forgot I was using the jQuery syntax in my shortcuts!  Confirmed that an alert('hi') works as expected.

That explains that; I can update my shortcuts to stop using the jQuery pointer.  Out of curiosity, what changed to prevent shortcuts from referencing jQuery if it exists on the page in question?

**Comment by araadt** [comment]
Sorry, I missed notifications. I'm having the same experience as @sonnyd64.

An initial click on the shortcut will reveal no code; after clicking into the text field the js will eventually populate. (It takes about 5-10 sec or so). After that given shortcut has then shown as below, if I close out of options and force-reload the page I typically use these shortcuts on, there is still no response from the script.

![image](https://user-images.githubusercontent.com/14303839/33049732-a90e06c6-ce1e-11e7-8608-8f4e8ca682ca.png)
![image](https://user-images.githubusercontent.com/14303839/33049747-b41a551a-ce1e-11e7-9001-db4e41a64c61.png)

**Comment by mikecrittenden** [comment]
Yeah, same issue for you @araadt - your code is relying on jQuery existing on the page, and the latest version doesn't allow that. 

@araadt, first of all, I'd rewrite your code as:

```
document.querySelectorAll('.btn-reason[data-reason="title_2"')[0].click();
```

That (untested obviously, but still) should remove the need for jQuery.

As for why this changed @sonnyd64, basically I went from doing this: https://github.com/mikecrittenden/chrome-shortkeys/commit/7d508d9dd40f5e726502a497baaed67b5ecc96ec#diff-5feac6cb4cde83d2ee21c4deb0a9f993L87 (i.e., programmatically creating a script tag and dumping it into the DOM to execute) to this: https://github.com/mikecrittenden/chrome-shortkeys/commit/7d508d9dd40f5e726502a497baaed67b5ecc96ec#diff-d99999859ee4ceaef47b1fe7acdc42afR217 (i.e., running `executeScript()` from the background). The reasoning for that change was that 1) it's cleaner and less hacky and 2) I'm trying to move as much as possible to the background rather than content scripts just to keep the actual content script that gets injected into the web pages lean and fast.

That said, I didn't realize that this would be a side effect of that, and I'm open to the idea of switching it back if enough people are missing this functionality.

How much of a pain is it for you two? And @AlexByte, you have any opinion here?

**Comment by mikecrittenden** [comment]
Spun up #84 to deal with the issue of the JS not loading until seconds after you click the box.

**Comment by sonnyd64** [comment]
Hmm, a lot of my shortcuts were focused on triggering DOM events which being able to use jQuery was certainly handy for.  I've been updating them to use traditional JS like your example above without much issue though, so I'd say it's a matter of convenience at best.

That said, I have noticed one oddity and I'm not sure if it's related or not so I'll hold off on spinning up a separate issue.  Is it possible that the above change would have disrupted the "Active while in form fields" setting?  Seems like that functionality is no longer working for me; I initially thought it was tied to jQuery but I confirmed that the "alert('hi')" and non-JS shortcuts also don't function when a textbox has focus.

**Comment by mikecrittenden** [comment]
Hmm, I'll check that out. 

Bear with me guys/gals - this was a pretty major overhaul that went live today (mainly to support #44 and #73).

**Comment by mikecrittenden** [comment]
Ok @sonnyd64 I just pushed 2.0.22 to the webstore which contains https://github.com/mikecrittenden/chrome-shortkeys/commit/8987da08a760ab5b1690355baf350f61065c5441 which should fix that "Active in form fields" checkbox. Sorry about that! I don't know how I missed that when testing today's release.

**Comment by mikecrittenden** [comment]
**Open question to anyone reading this: do you miss having things like jQuery from the page available to you in your custom JS?**

I'll leave this issue open for a while to see if anyone else is hitting this.

**Comment by jpalmieri** [comment]
@mikecrittenden yes, but it's forcing me to learn how to manipulate the DOM with vanilla JS like I should have in the first place haha.

Would it be feasible to have options to add in external scripts from CDNs (like on codepen.io), so the user could just include it if needed?

**Comment by Lotsofjoy** [comment]
I have 25 shortkeys programmed that all use jquery, as do many of the people I work with. I don't know how to re-write them all. Can they go back to working as is please?

**Comment by a-diagonal** [comment]
Absolutely, definitely, positively need jquery. Not just selectors but functions as well.

The problem with this extension is that it uses (or, at least, did use) storage.sync which filled up pretty fast necessitating the use of jquery to lighten the code base.

**Comment by a-diagonal** [comment]
I'd also like to take a moment to mention that the tiny little interface we have is unusable.

I have a screen the size of a small country and have to reach for my binoculars to use this extension.

**Comment by sirius16** [comment]
There are certain libraries, like jQuery UI, that absolutely require jQuery so...

**Comment by mikecrittenden** [comment]
@sirius16 you're using jQuery UI in your custom shortcuts?

**Comment by sirius16** [comment]
In a couple yeah (also, damn, that was quick)

**Comment by mikecrittenden** [comment]
Ok, it seems like it's fair to say that there are more than just one or two people that were affected by this, so I switched it back in https://github.com/mikecrittenden/chrome-shortkeys/commit/1a30e277f86cf18a6837f3b331ba552fb9c15c0d and just pushed 2.0.23 to the webstore which contains that fix.

**Thank you everyone for the feedback and thoughts! It's super awesome to see all the cool stuff you guys are doing with Shortkeys. Keep it coming!**

**Comment by sirius16** [comment]
Thank you

**Comment by a-diagonal** [comment]
Amazing + I love you 4 evar.

Thanks.

**Comment by mikecrittenden** [comment]
@a-diagonal by the way, seems like you might already know this, but just in case - #67 fixed the size limit bug - it now falls back to local storage if your settings are too large to sync, and it just gives you a message that everything will still work but it won't sync to your other Chrome installations. 

Also @a-diagonal the version I just pushed to the webstore bumps the width of the popup up to 750px. Chrome is deprecating the "separate tab for options" thing (see https://developer.chrome.com/extensions/optionsV2#open_in_tab) and I'm not super happy about it, because of crap like this. There's no way that I can see to say "make the popup take 80% of the window width" or something so I'm hesitant to set it much bigger than 750px since that will overflow the window if someone has their window small for whatever reason. See if that is any better for you.

Before:

![before](https://user-images.githubusercontent.com/32261/33079570-f1dfe3da-cea3-11e7-9e59-bf3d58952014.png)

After:

![after](https://user-images.githubusercontent.com/32261/33079575-f5976980-cea3-11e7-8980-88406b3d1fef.png)

**P.S. Reviews appreciated! People keep posting 1 star reviews, saying that it doesn't work. https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck/reviews?hl=en-US&gl=US**

**Comment by a-diagonal** [comment]
Thanks for the width fix. Also, thanks for the heads-up on the pending options page change + the storage issue that you have addressed.

Review ***** on webstore done.

**Comment by araadt** [comment]
Thanks for being so responsive, Mike. I have a number of coworkers, too, that have come to rely on your work in the day-to-day. We appreciate it.

**Comment by mikecrittenden** [comment]
My pleasure! Thanks for the kind words and keep the feedback coming!
