### ISSUE TITLE
Putting JS in the text box that wraps to the next line makes the popup resize endlessly

### ISSUE THREAD

**Issue by nurban3794** [mikecrittenden/chrome-shortkeys#86]
Most of my shortkeys are "Run Javascript," and none of them seem to be working. Whenever I try to edit a shortkey's javascript, the screen continuously expands and collapses, making it impossible to edit the code or even click the "Save" button. I tried to delete the shortkey entirely and add a new one with the same code but, as soon as I paste the code into the appropriate box, the screen starts to expand/collapse like it does when I edit the existing javascript

**Comment by mikecrittenden** [comment]
#83 might have fixed the issue with your shortcuts not working, depending on what exactly you're doing in the JS. 

The expanding and collapsing also might have been fixed in the latest release since I increased the width of the popup, which may be what the problem was. See this comment: https://github.com/mikecrittenden/chrome-shortkeys/issues/83#issuecomment-346055701

Wait until you get 2.0.23 (you can go to chrome://extensions, check "Developer mode", and click "Update all extensions" to try to speed it up) and then try again and let me know how it goes.

**Comment by mikecrittenden** [comment]
It seems like it's an issue with line wrapping - like the JS code box and the popup start competing for growing/shrinking forever. As a quick workaround, try to make sure none of your lines of code are too long to fit in the 750px popup (in the latest version), and that should stop the expanding/collapsing.

**Comment by zellerpress** [comment]
having this problem too. Fixing the line wrap in textedit and then pasting it back in does fix the endless resizing, but it also for some reason broke its ability to do the script. Nothing else changed beside line wrap.

**Comment by mikecrittenden** [comment]
This should be fixed in the latest version (2.1.0).
